import { StyleSheet } from 'react-native';
import { APP_COLORS } from '../../constants/colors';

export const getStyles = (colors: any) => StyleSheet.create({
  keyboardContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 24,
  },
  scrollContainerWeb: {
    paddingHorizontal: 0,
  },
  pageContainer: {
    width: '100%',
    alignSelf: 'center',
  },
  pageContainerWeb: {
    width: '70%',
    maxWidth: 1000,
    minWidth: 320,
    alignSelf: 'center',
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    alignItems: 'center',
    marginBottom: 32,
    position: 'relative',
    width: '100%',
  },
  backButton: {
    position: 'absolute',
    left: 0,
    top: 0,
    padding: 8,
    zIndex: 1,
    backgroundColor: colors.cardBackground || APP_COLORS.background.lightGray,
    borderRadius: 20,
  },
  iconContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: colors.cardBackground || APP_COLORS.background.lightGray,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: colors.text || APP_COLORS.text.primary,
    marginTop: 8,
    marginBottom: 8,
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 15,
    color: colors.textSecondary || APP_COLORS.text.secondary,
    textAlign: 'center',
    paddingHorizontal: 20,
    lineHeight: 22,
  },
  optionsContainer: {
    width: '100%',
    gap: 16,
  },
  roleOption: {
    backgroundColor: colors.cardBackground || APP_COLORS.background.white,
    paddingVertical: 24,
    paddingHorizontal: 20,
    borderRadius: 16,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  roleOptionCreate: {
    borderColor: APP_COLORS.primary.lighter,
  },
  roleOptionJoin: {
    borderColor: '#D4EFDF',
  },
  roleOptionWeb: {
    alignSelf: 'stretch',
    width: '100%',
    marginHorizontal: 0,
  },
  roleIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  roleIconContainerCreate: {
    backgroundColor: APP_COLORS.primary.lighter,
  },
  roleIconContainerJoin: {
    backgroundColor: '#D4EFDF',
  },
  roleTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.text || APP_COLORS.text.primary,
    marginBottom: 6,
  },
  roleDescription: {
    fontSize: 13,
    color: colors.textSecondary || APP_COLORS.text.secondary,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 8,
  },
  formContainer: {
    width: '100%',
    gap: 16,
  },
  inputContainer: {
    width: '100%',
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text || APP_COLORS.text.primary,
    marginBottom: 8,
    marginLeft: 4,
  },
  input: {
    backgroundColor: colors.inputBackground || APP_COLORS.background.lightGray,
    padding: 16,
    borderRadius: 12,
    fontSize: 16,
    borderWidth: 1.5,
    borderColor: colors.border || APP_COLORS.border.light,
    color: colors.text || APP_COLORS.text.primary,
  },
  inputFocused: {
    borderColor: APP_COLORS.primary.main,
    backgroundColor: colors.cardBackground || APP_COLORS.background.white,
  },
  codeInput: {
    textAlign: 'center',
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: 8,
    paddingVertical: 20,
  },
  primaryButton: {
    backgroundColor: APP_COLORS.primary.main,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    shadowColor: APP_COLORS.primary.main,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  primaryButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },
  disabledButton: {
    backgroundColor: colors.textSecondary || '#ccc',
    shadowOpacity: 0,
    elevation: 0,
  },
  inviteCodeBox: {
    marginTop: 20,
    padding: 20,
    backgroundColor: APP_COLORS.status.successLight,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: APP_COLORS.status.success,
  },
  inviteCodeLabel: {
    fontSize: 13,
    color: APP_COLORS.status.successDark,
    fontWeight: '500',
    marginBottom: 8,
  },
  inviteCodeText: {
    fontSize: 28,
    fontWeight: '800',
    color: APP_COLORS.status.success,
    letterSpacing: 4,
  },
  inviteCodeHint: {
    fontSize: 12,
    color: APP_COLORS.status.successDark,
    marginTop: 8,
    textAlign: 'center',
  },
  // Backward compatibility
  inviteCodeBoxInline: {
    marginTop: 20,
    padding: 20,
    backgroundColor: APP_COLORS.status.successLight,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: APP_COLORS.status.success,
  },
  inviteCodeLabelInline: {
    fontSize: 13,
    color: APP_COLORS.status.successDark,
    fontWeight: '500',
  },
  inviteCodeTextInline: {
    marginTop: 8,
    fontSize: 28,
    fontWeight: '800',
    color: APP_COLORS.status.success,
    letterSpacing: 4,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 32,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: colors.border || APP_COLORS.border.light,
  },
  logoutButtonText: {
    fontSize: 14,
    color: colors.textSecondary || APP_COLORS.text.secondary,
    marginLeft: 8,
    fontWeight: '600',
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 24,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.border || APP_COLORS.border.light,
  },
  dividerText: {
    paddingHorizontal: 16,
    fontSize: 13,
    color: colors.textSecondary || APP_COLORS.text.secondary,
    fontWeight: '500',
  },
  helpText: {
    fontSize: 13,
    color: colors.textSecondary || APP_COLORS.text.secondary,
    textAlign: 'center',
    marginTop: 12,
    lineHeight: 20,
  },
});
