// Firestore pode vir de duas fontes:
// - Mobile nativo: '@react-native-firebase/firestore'
// - Web: SDK modular 'firebase/firestore'
// Fazemos detecção simples baseada em plataforma.
import { addDoc, collection, deleteDoc, doc, getFirestore, onSnapshot, query, serverTimestamp, updateDoc, where } from 'firebase/firestore';
import React, { createContext, ReactNode, useContext, useEffect, useMemo, useState } from 'react';
import { Platform } from 'react-native';
import { TaskData } from '../components/Task';
import { app } from '../config/firebase';
import { useAuth } from './AuthContext';
import { useCategories } from './CategoryContext';
let nativeFirestore: any = null;
try {
  // Só tenta importar o pacote nativo fora do ambiente web
  if (Platform.OS !== 'web') {
    nativeFirestore = require('@react-native-firebase/firestore').default;
  }
} catch (e) {
  nativeFirestore = null;
}

// Omit 'id' as it will be generated by Firestore
type TaskInput = Omit<TaskData, 'id'>;

interface TaskContextData {
  tasks: TaskData[];
  loading: boolean;
  addTask: (task: TaskInput) => Promise<void>;
  updateTask: (task: TaskData) => Promise<void>;
  deleteTask: (id: string) => Promise<void>;
  approveTask: (id: string) => Promise<void>;
  rejectTask: (id: string) => Promise<void>;
  toggleComplete: (id: string) => Promise<void>;
  getUserName: (uid?: string) => string | undefined; // added function signature
  categoryCounts: Record<string, number>; // categoryId -> count de tarefas (não deletadas)
}

const TaskContext = createContext<TaskContextData>({} as TaskContextData);

export const useTasks = () => {
  return useContext(TaskContext);
};

interface TaskProviderProps {
  children: ReactNode;
}

export const TaskProvider = ({ children }: TaskProviderProps) => {
  const { user } = useAuth();
  const { categories } = useCategories();
  const [tasks, setTasks] = useState<TaskData[]>([]);
  const [loading, setLoading] = useState(true);
  const [userNames, setUserNames] = useState<Record<string,string>>({});
  const prevTasksRef = React.useRef<TaskData[]>([]);
  const [categoryCounts, setCategoryCounts] = useState<Record<string, number>>({});

  // Use a memoized reference to the collection
  const tasksCollection = useMemo(() => {
    if (nativeFirestore) {
      return nativeFirestore().collection('tasks');
    }
    // Web path (modular)
    const db = getFirestore(app);
    return collection(db, 'tasks');
  }, []);

  useEffect(() => {
      if (user && user.familyId) {
      setLoading(true);
      let unsubscribe: (() => void) | undefined;
      if (nativeFirestore) {
        unsubscribe = tasksCollection
          .where('familyId', '==', user.familyId)
          .onSnapshot((querySnapshot: any) => {
            const tasksData: TaskData[] = querySnapshot.docs.map((d: any) => ({
              id: d.id,
              ...d.data(),
            } as TaskData));
            handleIncomingTasks(tasksData);
            setLoading(false);
          }, (error: any) => {
            console.error('Erro ao buscar tarefas (nativo): ', error);
            setLoading(false);
          });
      } else {
        // Web (modular)
        const db = getFirestore(app);
        const q = query(collection(db, 'tasks'), where('familyId', '==', user.familyId));
        unsubscribe = onSnapshot(q, (querySnapshot) => {
          const tasksData: TaskData[] = querySnapshot.docs.map(d => ({
            id: d.id,
            ...(d.data() as any),
          }));
            handleIncomingTasks(tasksData);
          setLoading(false);
        }, (error) => {
          console.error('Erro ao buscar tarefas (web): ', error);
          setLoading(false);
        });
      }

      // Unsubscribe from snapshot listener when component unmounts
      return () => {
        if (unsubscribe) {
          unsubscribe();
        }
      };
    } else {
      setTasks([]);
      setLoading(false);
    }
  }, [user, tasksCollection]);


  const fetchUserName = async (uid: string) => {
    if (userNames[uid] || !uid) return;
    try {
      if (nativeFirestore) {
        const docSnap = await nativeFirestore().collection('users').doc(uid).get();
        if (docSnap.exists()) {
          setUserNames(prev => ({ ...prev, [uid]: docSnap.data().displayName || 'Usuário' }));
        }
      } else {
        const db = getFirestore(app);
        // lazy import doc/getDoc only if needed? Already imported doc, getDoc above.
        const { doc: docFn, getDoc } = await import('firebase/firestore');
        const snap = await getDoc(docFn(db, 'users', uid));
        if (snap.exists()) {
          const data: any = snap.data();
          setUserNames(prev => ({ ...prev, [uid]: data.displayName || 'Usuário' }));
        }
      }
    } catch (e) {
      console.warn('Não foi possível obter nome do usuário', uid, e);
    }
  };

  const handleIncomingTasks = (incoming: TaskData[]) => {
    // Detect status transitions for notification (pending -> approved/rejected)
    const prev = prevTasksRef.current;
    const changed = incoming.filter(t => {
      const old = prev.find(p => p.id === t.id);
      if (!old) return false;
      return old.status === 'pending' && (t.status === 'approved' || t.status === 'rejected');
    });
    if (changed.length && user) {
      changed.forEach(t => {
        if (t.createdBy === user.uid && t.status !== 'pending') {
          const statusMsg = t.status === 'approved' ? 'aprovada' : 'rejeitada';
          // Simples notificação local (console + alert em ambiente RN)
          console.log(`Tarefa '${t.title}' ${statusMsg}.`);
          try {
            // Evita chamar alert em ambientes sem suporte
            // eslint-disable-next-line @typescript-eslint/no-var-requires
            const { Alert } = require('react-native');
            Alert.alert('Atualização de tarefa', `Sua tarefa "${t.title}" foi ${statusMsg}.`);
          } catch {}
        }
      });
    }
    // Pre-fetch user names for createdBy / approvedBy
    const uids = new Set<string>();
    incoming.forEach(t => {
      if (t.createdBy) uids.add(t.createdBy);
      if (t.approvedBy) uids.add(t.approvedBy);
    });
    uids.forEach(uid => fetchUserName(uid));
    prevTasksRef.current = incoming;
    setTasks(incoming);
    // Atualiza contagem por categoryId (ou fallback: category string mapeada) - apenas tarefas não removidas
    const counts: Record<string, number> = {};
    incoming.forEach(t => {
      const key = t.categoryId || ''; // se ainda não migrado, ignorar até migração acontecer
      if (!key) return;
      counts[key] = (counts[key] || 0) + 1;
    });
    setCategoryCounts(counts);
  };

  const getUserName = (uid?: string) => {
    if (!uid) return undefined;
    return userNames[uid];
  };

  const addTask = async (task: TaskInput) => {
    if (!user || !user.familyId) {
      throw new Error("Usuário não autenticado ou sem família associada.");
    }
    const base = {
      ...task,
      createdBy: user.uid,
      familyId: user.familyId,
      status: user.role === 'admin' ? 'approved' : 'pending',
      createdAt: nativeFirestore ? nativeFirestore.FieldValue.serverTimestamp() : serverTimestamp(),
    } as any;
    if (nativeFirestore) {
      await tasksCollection.add(base);
    } else {
      const db = getFirestore(app);
      await addDoc(collection(db, 'tasks'), base);
    }
  };

  const updateTask = async (task: TaskData) => {
    const { id, ...taskData } = task;
    if (nativeFirestore) {
      await tasksCollection.doc(id).update(taskData);
    } else {
      const db = getFirestore(app);
      await updateDoc(doc(db, 'tasks', id), taskData as any);
    }
  };

  const deleteTask = async (id: string) => {
    if (nativeFirestore) {
      await tasksCollection.doc(id).delete();
    } else {
      const db = getFirestore(app);
      await deleteDoc(doc(db, 'tasks', id));
    }
  };

  const approveTask = async (id: string) => {
    if (!user) return;
    const update = { status: 'approved', approvedBy: user.uid } as any;
    if (nativeFirestore) {
      await tasksCollection.doc(id).update(update);
    } else {
      const db = getFirestore(app);
      await updateDoc(doc(db, 'tasks', id), update);
    }
  };

  const rejectTask = async (id: string) => {
    if (!user) return;
    const update = { status: 'rejected', approvedBy: user.uid } as any;
    if (nativeFirestore) {
      await tasksCollection.doc(id).update(update);
    } else {
      const db = getFirestore(app);
      await updateDoc(doc(db, 'tasks', id), update);
    }
  };

  const toggleComplete = async (id: string) => {
    const task = tasks.find(t => t.id === id);
    if (!task) return;
    const update = { completed: !task.completed, status: !task.completed ? 'completed' : (task.status === 'completed' ? 'approved' : task.status) } as any;
    if (nativeFirestore) {
      await tasksCollection.doc(id).update(update);
    } else {
      const db = getFirestore(app);
      await updateDoc(doc(db, 'tasks', id), update);
    }
  };

  const value = {
    tasks,
    loading,
    addTask,
    updateTask,
    deleteTask,
    approveTask,
    rejectTask,
    toggleComplete,
    getUserName,
    categoryCounts,
  };

  return <TaskContext.Provider value={value}>{children}</TaskContext.Provider>;
};
