import { StyleSheet } from 'react-native';
import { APP_COLORS } from '../../constants/colors';

const THEME = {
    primary: APP_COLORS.primary.main,
    danger: APP_COLORS.status.error,
    success: APP_COLORS.status.success,
    warning: APP_COLORS.status.warning,
    textPrimary: APP_COLORS.text.primary,
    textSecondary: APP_COLORS.text.secondary,
};

export const getHeaderStyles = (colors: any) => StyleSheet.create({
  // Container Styles
  container: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: colors.surface,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 3,
    zIndex: 1000,
  },
  containerOnline: {
    shadowColor: APP_COLORS.status.success,
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  containerError: {
    shadowColor: APP_COLORS.status.error,
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  containerOffline: {
    shadowColor: APP_COLORS.status.warning,
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  leftSection: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  rightSection: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    marginLeft: 16,
  },
  notificationIconContainer: {
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  notificationDot: {
    position: 'absolute',
    top: -4,
    right: -2,
    backgroundColor: APP_COLORS.status.error,
    borderRadius: 8,
    minWidth: 16,
    height: 16,
    paddingHorizontal: 3,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: APP_COLORS.background.lightGray,
  },
  notificationDotText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  // Modal Styles
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: '95%',
    maxWidth: 500,
    backgroundColor: colors.surface,
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
    maxHeight: '75%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 15,
    color: colors.textPrimary,
  },
  input: {
    width: '100%',
    borderWidth: 1,
    borderColor: APP_COLORS.border.light,
    borderRadius: 5,
    padding: 10,
    marginBottom: 20,
    fontSize: 16,
    color: colors.textPrimary,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  modalButton: {
    flex: 1,
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: '#ccc',
    marginRight: 10,
  },
  saveButton: {
    backgroundColor: APP_COLORS.primary.main,
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  // Specific for JoinFamilyModal
  errorText: {
    color: APP_COLORS.status.error,
    alignSelf: 'flex-start',
    marginTop: -12,
    marginBottom: 8,
  },
  // Specific for AvatarActions
  modalButtonsColumn: {
    width: '100%',
    gap: 10,
  },
  fullWidthButton: {
    width: '100%',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryBtn: {
    backgroundColor: APP_COLORS.secondary.main,
  },
  cancelBtn: {
    backgroundColor: '#ccc',
  },
  cancelButtonText: {
    color: '#333',
    fontWeight: 'bold',
  },
  // Specific for ProfileSettingsModal
  roleSelectionTitle: {
    fontSize: 16,
    marginBottom: 15,
    color: colors.textSecondary,
    alignSelf: 'flex-start',
  },
  roleOptionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 20,
    gap: 10,
  },
  roleOption: {
    flex: 1,
    borderWidth: 1,
    borderColor: APP_COLORS.border.light,
    borderRadius: 10,
    padding: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  roleOptionSelected: {
    backgroundColor: APP_COLORS.primary.main,
    borderColor: APP_COLORS.primary.main,
  },
  roleOptionText: {
    marginTop: 8,
    fontWeight: '600',
    color: APP_COLORS.primary.main,
    fontSize: 14,
  },
  roleOptionTextSelected: {
    color: '#fff',
  },
  roleDescription: {
    marginTop: 4,
    fontSize: 11,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  roleDescriptionSelected: {
    color: 'rgba(255, 255, 255, 0.8)',
  },
  saveButtonText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  // Avatar Styles
  avatarContainer: {
    position: 'relative',
    marginRight: 20,
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
  },
  defaultAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.border,
  },
  christmasHat: {
    position: 'absolute',
    top: -19,
    right: -8,
    width: 35,
    height: 35,
    zIndex: 10,
    resizeMode: 'contain',
  },
  editIconContainer: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    backgroundColor: APP_COLORS.primary.main,
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: APP_COLORS.background.lightGray,
  },
  iconAvatar: {
    backgroundColor: APP_COLORS.primary.light,
    borderColor: '#d3e6ff',
  },
  avatarEmoji: {
    fontSize: 40,
    textAlign: 'center',
    width: '100%',
    alignSelf: 'center',
  },
  loadingOverlay: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    borderRadius: 12,
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Icon Picker Styles
  iconModalContent: {
    maxHeight: '75%',
  },
  iconScrollView: {
    maxHeight: 400,
  },
  iconScrollContent: {
    paddingBottom: 10,
  },
  iconGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  iconOption: {
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: '#f1f5f9',
    justifyContent: 'center',
    alignItems: 'center',
    margin: 6,
    borderWidth: 1,
    borderColor: '#dce3ea'
  },
  iconOptionSelected: {
    backgroundColor: APP_COLORS.primary.light,
    borderColor: APP_COLORS.primary.main,
    borderWidth: 2,
  },
  emojiIcon: {
    fontSize: 32,
  },
  primaryButton: {
    backgroundColor: APP_COLORS.primary.main,
  },
  // Avatar Actions Modal
  dangerBtn: {
    backgroundColor: APP_COLORS.status.error,
  },
  // Calendar Styles
  calendarCenterOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullscreenOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'transparent',
  },
  calendarModalCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingVertical: 8,
    width: '95%',
    maxWidth: 500,
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 10,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  eventsScrollContainer: {
    maxHeight: 300,
    flexGrow: 0,
  },
  holidayListContainer: {
    marginTop: 6,
    gap: 4,
  },
  legendContainer: {
    backgroundColor: colors.inputBackground,
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  legendTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: 8,
  },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  legendDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 8,
  },
  legendText: {
    fontSize: 11,
    color: colors.textSecondary,
    flex: 1,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: 8,
    marginTop: 4,
  },
  eventCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  eventIndicator: {
    width: 4,
    height: '100%',
    borderRadius: 2,
    marginRight: 10,
  },
  eventContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  eventDate: {
    fontSize: 12,
    fontWeight: 'bold',
    color: colors.textSecondary,
    minWidth: 45,
  },
  eventTitle: {
    fontSize: 13,
    color: colors.textPrimary,
    flex: 1,
  },
  holidayListEmpty: {
    fontSize: 12,
    color: colors.textSecondary,
    fontStyle: 'italic',
  },
  // UserInfo Styles
  userInfo: {
    flex: 1,
    paddingHorizontal: 10,
  },
  nameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  userName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.textPrimary,
    marginBottom: 4,
  },
  editNameIcon: {
    marginLeft: 0,
  },
  subtitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  subtitle: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  syncPill: {
    marginLeft: 8,
    backgroundColor: APP_COLORS.primary.main,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
  },
  syncPillText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '600',
  },
  // Menu Styles
  menuContainer: {
    position: 'relative',
    zIndex: 9999,
  },
  modalRoot: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  dropdownMenuModal: {
    position: 'absolute',
    // top e right são calculados dinamicamente
    width: 240,
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 12,
    maxHeight: 400,
    zIndex: 1001,
    overflow: 'hidden',
  },
  menuScrollView: {
    maxHeight: 400,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: '#f3f4f6',
    minHeight: 52,
  },
  menuText: {
    fontSize: 15,
    fontWeight: '500',
    color: colors.textPrimary,
    flex: 1,
  },
  segmentedControl: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surfaceSecondary,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
    width: '100%',
  },
  segment: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentActive: {
    backgroundColor: APP_COLORS.primary.main,
  },
  segmentText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  segmentTextActive: {
    color: '#fff',
  },
});

